# Generated by Django 5.1.3 on 2024-11-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XRayDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('xray_type', models.CharField(max_length=50)),
                ('diagnosis_summary', models.TextField()),
                ('detailed_findings', models.TextField()),
                ('date_of_diagnosis', models.DateField(auto_now_add=True)),
                ('radiologist_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'X-ray Diagnosis',
                'verbose_name_plural': 'X-ray Diagnoses',
                'ordering': ['-date_of_diagnosis'],
            },
        ),
    ]
